{
 "title": "Logging Dashboard Hid10001087",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "ERROR" }
  ]
 },
 "panels": [
  {
   "title": "Live nginx logs",
   "type": "table",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_deployment_name=\"nginx\"} |= ``"
    }
   ]
  },
  {
   "title": "CPU % usage per node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (instance) (\n    rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])\n  )\n) / ON(instance)\n(\n  count by (instance) (node_cpu_seconds_total{mode=\"idle\"})\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Memory % usage per node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(label_replace(container_memory_working_set_bytes{id=\"/\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node)\n/\non(node) max(kube_node_status_allocatable{resource=\"memory\"}) by (node)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live nginx errors",
   "type": "table",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_deployment_name=\"nginx\", nginx_status!=\"200\", service_name=\"nginx\"} |= ``"
    }
   ]
  },
  {
   "title": "Disk % capacity usage per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live ingress nginx logs",
   "type": "table",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_deployment_name=\"nginx-ingress-nginx-ingress-controller\"} |= ``"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count: of  nginx $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of nginx $searchable_pattern in the specified time range",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({k8s_deployment_name=\"nginx\", nginx_status!=\"200\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Top Requested Ingress Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "topk(5, sum by (host) (increase(nginx_ingress_controller_requests[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress requests per status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (code_group) (\n  label_replace(\n    increase(nginx_ingress_controller_requests{status=~\"2..\"}[$__range]),\n    \"code_group\",\n    \"2xx\",\n    \"status\",\n    \".*\"\n  )\n  or label_replace(\n    increase(nginx_ingress_controller_requests{status=~\"3..\"}[$__range]),\n    \"code_group\",\n    \"3xx\",\n    \"status\",\n    \".*\"\n  )\n  or label_replace(\n    increase(nginx_ingress_controller_requests{status=~\"4..\"}[$__range]),\n    \"code_group\",\n    \"4xx\",\n    \"status\",\n    \".*\"\n  )\n  or label_replace(\n    increase(nginx_ingress_controller_requests{status=~\"5..\"}[$__range]),\n    \"code_group\",\n    \"5xx\",\n    \"status\",\n    \".*\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}