FROM common-dockerhub-remote.jfrog.teliacompany.io/bitnami/nginx:latest

USER root 

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/* \
    apt-get update && apt-get install -y ca-certificates
USER nginx  

CMD ["nginx", "-g", "daemon off;"]
