apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: telia-acme
spec:
  acme:
    server: "https://acme.trust.telia.com/directory"
    externalAccountBinding:
      keyID: TELIA_ACME_KEY_ID
      keySecretRef:
        name: telia-acme-key
        key: acme_hmac  
    email: api-solutions@teliacompany.com
    privateKeySecretRef:
      name: acme-prod
    solvers:
      - http01:
          ingress:
            class: nginx
            