apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster-cl-alf-dso-e-dev-00
  namespace: devexpc
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes_dev_tanzu_d0
          role: vault-kube
          serviceAccountRef:
            name: vault-auth-devexp
            namespace: devexpc
      namespace: Hid100009299
      path: kv
      server: https://se.kms-stage.teliacompany.net/
      version: v2

