apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "cluster-external-secret-docker"
spec:
  externalSecretName: "devexp-docker-eso"
  namespaceSelector:
    matchLabels:
      clusterexternalsecret: enabled
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: "15s"
    secretStoreRef:
      name: vault-backend-cluster-cl-alf-dso-e-dev-00
      kind: ClusterSecretStore
    target:
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ .vaultdata | toString }}"
      name: pcoc-docker-eso
    data:
    - secretKey: vaultdata
      remoteRef:
        key: kv/jfrog.teliacompany.io/pcoc-docker-credentials
        property: docker-remote-helm
