
image:
  repository: common-ghcr-docker-remote.jfrog.teliacompany.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
  tag: ""
  # -- The flavour of tag you want to use
  # There are different image flavours available, like distroless and ubi.
  # Please see GitHub release notes for image tags for these flavors.
  # By default the distroless image is used.
  flavour: ""

# -- If set, install and upgrade CRDs through helm chart.
installCRDs: true

crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: true
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: true
  # -- If true, create CRDs for Push Secret.
  createPushSecret: true
  annotations: {}
  conversion:
    enabled: true

imagePullSecrets:
  - name: artifactory-secret
namespaceOverride: "devexpc"

webhook:
  # -- Specifies whether a webhook deployment be created.
  create: true
  certDir: /tmp/certs
  image:
    repository: common-ghcr-docker-remote.jfrog.teliacompany.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    
  imagePullSecrets:
    - name: artifactory-secret


certController:
  # -- Specifies whether a certificate controller deployment be created.
  create: true
  image:
    repository: common-ghcr-docker-remote.jfrog.teliacompany.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent

  imagePullSecrets:
    - name: artifactory-secret
  